### ISSUE TITLE
checking if possible

### ISSUE THREAD

**Issue by JohnnyCosta** [mrred85/vscode-theme-darcula#1]
I think this theme is amazing good.

I just wonder if it possible to change the colors on the package declaration for Java syntax as show here:
![sans titre](https://user-images.githubusercontent.com/3283905/42367722-64eddf12-8105-11e8-984a-f4cb0d5fced2.png)
for example put the import in orange the the name of the packages on a different color like white.

Is that possible?

**Comment by mrred85** [comment]
For the first, thank you for the appreciation. I fixed that in the last commit.
